#include "stdafx.h"
#include <stdio.h>
#include "C32Control.h"

// ∫Í∂®“Â
#if(_WIN32_WCE < 0x0400)
#define LB_MULTIPLEADDSTRING    0x01B1
#endif

BOOL g_C32DbgFlagLvNotifyFilter = FALSE;
BOOL g_C32DbgFlagLvNotify = TRUE;
BOOL g_C32DbgFlagHeaderNotify = TRUE;
BOOL g_C32DbgFlagWindowMsg = FALSE;
BOOL g_C32DbgFlagHeaderNotifyFilter = FALSE;
BOOL g_C32DbgFlagTabCtrlNotify = TRUE;
BOOL g_C32DbgFlagToolTipCtrlNotify = TRUE;
BOOL g_C32DbgFlagWmFilter = TRUE;

extern ULONG DebugOutputCount;


struct TValueString
{
	int Value;
	CHAR* String;
};

TValueString g_WmString[]={
	{WM_NULL,  "WM_NULL"},
	{WM_CREATE,  "WM_CREATE"},
	{WM_DESTROY,  "WM_DESTROY"},
	{WM_MOVE,  "WM_MOVE"},
	{WM_SIZE,  "WM_SIZE"},
	{WM_ACTIVATE,  "WM_ACTIVATE"},
	{WM_SETFOCUS,  "WM_SETFOCUS"},
	{WM_KILLFOCUS,  "WM_KILLFOCUS"},
	{WM_ENABLE,  "WM_ENABLE"},
	{WM_SETREDRAW,  "WM_SETREDRAW"},
	{WM_SETTEXT,  "WM_SETTEXT"},
	{WM_GETTEXT,  "WM_GETTEXT"},
	{WM_GETTEXTLENGTH,  "WM_GETTEXTLENGTH"},
	{WM_PAINT,  "WM_PAINT"},
	{WM_CLOSE,  "WM_CLOSE"},
	{WM_QUERYENDSESSION,  "WM_QUERYENDSESSION"},
	{WM_QUERYOPEN,  "WM_QUERYOPEN"},
	{WM_ENDSESSION,  "WM_ENDSESSION"},
	{WM_QUIT,  "WM_QUIT"},
	{WM_ERASEBKGND,  "WM_ERASEBKGND"},
	{WM_SYSCOLORCHANGE,  "WM_SYSCOLORCHANGE"},
	{WM_SHOWWINDOW,  "WM_SHOWWINDOW"},
	{WM_WININICHANGE,  "WM_WININICHANGE"},
	{WM_SETTINGCHANGE,  "WM_SETTINGCHANGE"},
	{WM_DEVMODECHANGE,  "WM_DEVMODECHANGE"},
	{WM_ACTIVATEAPP,  "WM_ACTIVATEAPP"},
	{WM_FONTCHANGE,  "WM_FONTCHANGE"},
	{WM_TIMECHANGE,  "WM_TIMECHANGE"},
	{WM_CANCELMODE,  "WM_CANCELMODE"},
	{WM_SETCURSOR,  "WM_SETCURSOR"},
	{WM_MOUSEACTIVATE,  "WM_MOUSEACTIVATE"},
	{WM_CHILDACTIVATE,  "WM_CHILDACTIVATE"},
	{WM_QUEUESYNC,  "WM_QUEUESYNC"},
	{WM_GETMINMAXINFO,  "WM_GETMINMAXINFO"},
	{WM_PAINTICON,  "WM_PAINTICON"},
	{WM_ICONERASEBKGND,  "WM_ICONERASEBKGND"},
	{WM_NEXTDLGCTL,  "WM_NEXTDLGCTL"},
	{WM_SPOOLERSTATUS,  "WM_SPOOLERSTATUS"},
	{WM_DRAWITEM,  "WM_DRAWITEM"},
	{WM_MEASUREITEM,  "WM_MEASUREITEM"},
	{WM_DELETEITEM,  "WM_DELETEITEM"},
	{WM_VKEYTOITEM,  "WM_VKEYTOITEM"},
	{WM_CHARTOITEM,  "WM_CHARTOITEM"},
	{WM_SETFONT,  "WM_SETFONT"},
	{WM_GETFONT,  "WM_GETFONT"},
	{WM_SETHOTKEY,  "WM_SETHOTKEY"},
	{WM_GETHOTKEY,  "WM_GETHOTKEY"},
	{WM_QUERYDRAGICON,  "WM_QUERYDRAGICON"},
	{WM_COMPAREITEM,  "WM_COMPAREITEM"},
	{WM_GETOBJECT,  "WM_GETOBJECT"},
	{WM_COMPACTING,  "WM_COMPACTING"},
	{WM_COMMNOTIFY,  "WM_COMMNOTIFY"},
	{WM_WINDOWPOSCHANGING,  "WM_WINDOWPOSCHANGING"},
	{WM_WINDOWPOSCHANGED,  "WM_WINDOWPOSCHANGED"},
	{WM_POWER,  "WM_POWER"},
	{WM_COPYDATA,  "WM_COPYDATA"},
	{WM_CANCELJOURNAL,  "WM_CANCELJOURNAL"},
	{WM_NOTIFY,  "WM_NOTIFY"},
	{WM_INPUTLANGCHANGEREQUEST,  "WM_INPUTLANGCHANGEREQUEST"},
	{WM_INPUTLANGCHANGE,  "WM_INPUTLANGCHANGE"},
	{WM_TCARD,  "WM_TCARD"},
	{WM_HELP,  "WM_HELP"},
	{WM_USERCHANGED,  "WM_USERCHANGED"},
	{WM_NOTIFYFORMAT,  "WM_NOTIFYFORMAT"},
	{WM_CONTEXTMENU,  "WM_CONTEXTMENU"},
	{WM_STYLECHANGING,  "WM_STYLECHANGING"},
	{WM_STYLECHANGED,  "WM_STYLECHANGED"},
	{WM_DISPLAYCHANGE,  "WM_DISPLAYCHANGE"},
	{WM_GETICON,  "WM_GETICON"},
	{WM_SETICON,  "WM_SETICON"},
	{WM_NCCREATE,  "WM_NCCREATE"},
	{WM_NCDESTROY,  "WM_NCDESTROY"},
	{WM_NCCALCSIZE,  "WM_NCCALCSIZE"},
	{WM_NCHITTEST,  "WM_NCHITTEST"},
	{WM_NCPAINT,  "WM_NCPAINT"},
	{WM_NCACTIVATE,  "WM_NCACTIVATE"},
	{WM_GETDLGCODE,  "WM_GETDLGCODE"},
	{WM_SYNCPAINT,  "WM_SYNCPAINT"},
	{WM_NCMOUSEMOVE,  "WM_NCMOUSEMOVE"},
	{WM_NCLBUTTONDOWN,  "WM_NCLBUTTONDOWN"},
	{WM_NCLBUTTONUP,  "WM_NCLBUTTONUP"},
	{WM_NCLBUTTONDBLCLK,  "WM_NCLBUTTONDBLCLK"},
	{WM_NCRBUTTONDOWN,  "WM_NCRBUTTONDOWN"},
	{WM_NCRBUTTONUP,  "WM_NCRBUTTONUP"},
	{WM_NCRBUTTONDBLCLK,  "WM_NCRBUTTONDBLCLK"},
	{WM_NCMBUTTONDOWN,  "WM_NCMBUTTONDOWN"},
	{WM_NCMBUTTONUP,  "WM_NCMBUTTONUP"},
	{WM_NCMBUTTONDBLCLK,  "WM_NCMBUTTONDBLCLK"},
	{WM_NCXBUTTONDOWN,  "WM_NCXBUTTONDOWN"},
	{WM_NCXBUTTONUP,  "WM_NCXBUTTONUP"},
	{WM_NCXBUTTONDBLCLK,  "WM_NCXBUTTONDBLCLK"},
	{WM_INPUT_DEVICE_CHANGE,  "WM_INPUT_DEVICE_CHANGE"},
	{WM_INPUT,  "WM_INPUT"},
	{WM_KEYFIRST,  "WM_KEYFIRST"},
	{WM_KEYDOWN,  "WM_KEYDOWN"},
	{WM_KEYUP,  "WM_KEYUP"},
	{WM_CHAR,  "WM_CHAR"},
	{WM_DEADCHAR,  "WM_DEADCHAR"},
	{WM_SYSKEYDOWN,  "WM_SYSKEYDOWN"},
	{WM_SYSKEYUP,  "WM_SYSKEYUP"},
	{WM_SYSCHAR,  "WM_SYSCHAR"},
	{WM_SYSDEADCHAR,  "WM_SYSDEADCHAR"},
	{WM_UNICHAR,  "WM_UNICHAR"},
	{WM_KEYLAST,  "WM_KEYLAST"},
	{WM_KEYLAST,  "WM_KEYLAST"},
	{WM_IME_STARTCOMPOSITION,  "WM_IME_STARTCOMPOSITION"},
	{WM_IME_ENDCOMPOSITION,  "WM_IME_ENDCOMPOSITION"},
	{WM_IME_COMPOSITION,  "WM_IME_COMPOSITION"},
	{WM_IME_KEYLAST,  "WM_IME_KEYLAST"},
	{WM_INITDIALOG,  "WM_INITDIALOG"},
	{WM_COMMAND,  "WM_COMMAND"},
	{WM_SYSCOMMAND,  "WM_SYSCOMMAND"},
	{WM_TIMER,  "WM_TIMER"},
	{WM_HSCROLL,  "WM_HSCROLL"},
	{WM_VSCROLL,  "WM_VSCROLL"},
	{WM_INITMENU,  "WM_INITMENU"},
	{WM_INITMENUPOPUP,  "WM_INITMENUPOPUP"},
	{WM_GESTURE,  "WM_GESTURE"},
	{WM_GESTURENOTIFY,  "WM_GESTURENOTIFY"},
	{WM_MENUSELECT,  "WM_MENUSELECT"},
	{WM_MENUCHAR,  "WM_MENUCHAR"},
	{WM_ENTERIDLE,  "WM_ENTERIDLE"},
	{WM_MENURBUTTONUP,  "WM_MENURBUTTONUP"},
	{WM_MENUDRAG,  "WM_MENUDRAG"},
	{WM_MENUGETOBJECT,  "WM_MENUGETOBJECT"},
	{WM_UNINITMENUPOPUP,  "WM_UNINITMENUPOPUP"},
	{WM_MENUCOMMAND,  "WM_MENUCOMMAND"},
	{WM_CHANGEUISTATE,  "WM_CHANGEUISTATE"},
	{WM_UPDATEUISTATE,  "WM_UPDATEUISTATE"},
	{WM_QUERYUISTATE,  "WM_QUERYUISTATE"},
	{WM_CTLCOLORMSGBOX,  "WM_CTLCOLORMSGBOX"},
	{WM_CTLCOLOREDIT,  "WM_CTLCOLOREDIT"},
	{WM_CTLCOLORLISTBOX,  "WM_CTLCOLORLISTBOX"},
	{WM_CTLCOLORBTN,  "WM_CTLCOLORBTN"},
	{WM_CTLCOLORDLG,  "WM_CTLCOLORDLG"},
	{WM_CTLCOLORSCROLLBAR,  "WM_CTLCOLORSCROLLBAR"},
	{WM_CTLCOLORSTATIC,  "WM_CTLCOLORSTATIC"},
	{WM_MOUSEMOVE,  "WM_MOUSEMOVE/FIRST"},
	{WM_LBUTTONDOWN,  "WM_LBUTTONDOWN"},
	{WM_LBUTTONUP,  "WM_LBUTTONUP"},
	{WM_LBUTTONDBLCLK,  "WM_LBUTTONDBLCLK"},
	{WM_RBUTTONDOWN,  "WM_RBUTTONDOWN"},
	{WM_RBUTTONUP,  "WM_RBUTTONUP"},
	{WM_RBUTTONDBLCLK,  "WM_RBUTTONDBLCLK"},
	{WM_MBUTTONDOWN,  "WM_MBUTTONDOWN"},
	{WM_MBUTTONUP,  "WM_MBUTTONUP"},
	{WM_MBUTTONDBLCLK,  "WM_MBUTTONDBLCLK"},
	{WM_MOUSEWHEEL,  "WM_MOUSEWHEEL"},
	{WM_XBUTTONDOWN,  "WM_XBUTTONDOWN"},
	{WM_XBUTTONUP,  "WM_XBUTTONUP"},
	{WM_XBUTTONDBLCLK,  "WM_XBUTTONDBLCLK"},
	{WM_MOUSEHWHEEL,  "WM_MOUSEHWHEEL"},
	{WM_MOUSELAST,  "WM_MOUSELAST"},
	{WM_MOUSELAST,  "WM_MOUSELAST"},
	{WM_MOUSELAST,  "WM_MOUSELAST"},
	{WM_MOUSELAST,  "WM_MOUSELAST"},
	{WM_PARENTNOTIFY,  "WM_PARENTNOTIFY"},
	{WM_ENTERMENULOOP,  "WM_ENTERMENULOOP"},
	{WM_EXITMENULOOP,  "WM_EXITMENULOOP"},
	{WM_NEXTMENU,  "WM_NEXTMENU"},
	{WM_SIZING,  "WM_SIZING"},
	{WM_CAPTURECHANGED,  "WM_CAPTURECHANGED"},
	{WM_MOVING,  "WM_MOVING"},
	{WM_POWERBROADCAST,  "WM_POWERBROADCAST"},
	{WM_DEVICECHANGE,  "WM_DEVICECHANGE"},
	{WM_MDICREATE,  "WM_MDICREATE"},
	{WM_MDIDESTROY,  "WM_MDIDESTROY"},
	{WM_MDIACTIVATE,  "WM_MDIACTIVATE"},
	{WM_MDIRESTORE,  "WM_MDIRESTORE"},
	{WM_MDINEXT,  "WM_MDINEXT"},
	{WM_MDIMAXIMIZE,  "WM_MDIMAXIMIZE"},
	{WM_MDITILE,  "WM_MDITILE"},
	{WM_MDICASCADE,  "WM_MDICASCADE"},
	{WM_MDIICONARRANGE,  "WM_MDIICONARRANGE"},
	{WM_MDIGETACTIVE,  "WM_MDIGETACTIVE"},
	{WM_MDISETMENU,  "WM_MDISETMENU"},
	{WM_ENTERSIZEMOVE,  "WM_ENTERSIZEMOVE"},
	{WM_EXITSIZEMOVE,  "WM_EXITSIZEMOVE"},
	{WM_DROPFILES,  "WM_DROPFILES"},
	{WM_MDIREFRESHMENU,  "WM_MDIREFRESHMENU"},
	{WM_TOUCH,  "WM_TOUCH"},
	{WM_IME_SETCONTEXT,  "WM_IME_SETCONTEXT"},
	{WM_IME_NOTIFY,  "WM_IME_NOTIFY"},
	{WM_IME_CONTROL,  "WM_IME_CONTROL"},
	{WM_IME_COMPOSITIONFULL,  "WM_IME_COMPOSITIONFULL"},
	{WM_IME_SELECT,  "WM_IME_SELECT"},
	{WM_IME_CHAR,  "WM_IME_CHAR"},
	{WM_IME_REQUEST,  "WM_IME_REQUEST"},
	{WM_IME_KEYDOWN,  "WM_IME_KEYDOWN"},
	{WM_IME_KEYUP,  "WM_IME_KEYUP"},
	{WM_MOUSEHOVER,  "WM_MOUSEHOVER"},
	{WM_MOUSELEAVE,  "WM_MOUSELEAVE"},
	{WM_NCMOUSEHOVER,  "WM_NCMOUSEHOVER"},
	{WM_NCMOUSELEAVE,  "WM_NCMOUSELEAVE"},
	{WM_WTSSESSION_CHANGE,  "WM_WTSSESSION_CHANGE"},
	{WM_TABLET_FIRST,  "WM_TABLET_FIRST"},
	{WM_TABLET_LAST,  "WM_TABLET_LAST"},
	{WM_CUT,  "WM_CUT"},
	{WM_COPY,  "WM_COPY"},
	{WM_PASTE,  "WM_PASTE"},
	{WM_CLEAR,  "WM_CLEAR"},
	{WM_UNDO,  "WM_UNDO"},
	{WM_RENDERFORMAT,  "WM_RENDERFORMAT"},
	{WM_RENDERALLFORMATS,  "WM_RENDERALLFORMATS"},
	{WM_DESTROYCLIPBOARD,  "WM_DESTROYCLIPBOARD"},
	{WM_DRAWCLIPBOARD,  "WM_DRAWCLIPBOARD"},
	{WM_PAINTCLIPBOARD,  "WM_PAINTCLIPBOARD"},
	{WM_VSCROLLCLIPBOARD,  "WM_VSCROLLCLIPBOARD"},
	{WM_SIZECLIPBOARD,  "WM_SIZECLIPBOARD"},
	{WM_ASKCBFORMATNAME,  "WM_ASKCBFORMATNAME"},
	{WM_CHANGECBCHAIN,  "WM_CHANGECBCHAIN"},
	{WM_HSCROLLCLIPBOARD,  "WM_HSCROLLCLIPBOARD"},
	{WM_QUERYNEWPALETTE,  "WM_QUERYNEWPALETTE"},
	{WM_PALETTEISCHANGING,  "WM_PALETTEISCHANGING"},
	{WM_PALETTECHANGED,  "WM_PALETTECHANGED"},
	{WM_HOTKEY,  "WM_HOTKEY"},
	{WM_PRINT,  "WM_PRINT"},
	{WM_PRINTCLIENT,  "WM_PRINTCLIENT"},
	{WM_APPCOMMAND,  "WM_APPCOMMAND"},
	{WM_THEMECHANGED,  "WM_THEMECHANGED"},
	{WM_CLIPBOARDUPDATE,  "WM_CLIPBOARDUPDATE"},
	{WM_DWMCOMPOSITIONCHANGED,  "WM_DWMCOMPOSITIONCHANGED"},
	{WM_DWMNCRENDERINGCHANGED,  "WM_DWMNCRENDERINGCHANGED"},
	{WM_DWMCOLORIZATIONCOLORCHANGED,  "WM_DWMCOLORIZATIONCOLORCHANGED"},
	{WM_DWMWINDOWMAXIMIZEDCHANGE,  "WM_DWMWINDOWMAXIMIZEDCHANGE"},
	{WM_DWMSENDICONICTHUMBNAIL,  "WM_DWMSENDICONICTHUMBNAIL"},
	{WM_DWMSENDICONICLIVEPREVIEWBITMAP,  "WM_DWMSENDICONICLIVEPREVIEWBITMAP"},
	{WM_GETTITLEBARINFOEX,  "WM_GETTITLEBARINFOEX"},
	{WM_HANDHELDFIRST,  "WM_HANDHELDFIRST"},
	{WM_HANDHELDLAST,  "WM_HANDHELDLAST"},
	{WM_AFXFIRST,  "WM_AFXFIRST"},
	{WM_AFXLAST,  "WM_AFXLAST"},
	{WM_PENWINFIRST,  "WM_PENWINFIRST"},
	{WM_PENWINLAST,  "WM_PENWINLAST"},
	{WM_APP,  "WM_APP"},
	{WM_USER,  "WM_USER"},
	{NULL, NULL }
};

/*
 * Edit Control Messages
 */

TValueString g_EditCtlMessageString[]=
{
	{EM_GETSEL,  "EM_GETSEL"},
	{EM_SETSEL,  "EM_SETSEL"},
	{EM_GETRECT,  "EM_GETRECT"},
	{EM_SETRECT,  "EM_SETRECT"},
	{EM_SETRECTNP,  "EM_SETRECTNP"},
	{EM_SCROLL,  "EM_SCROLL"},
	{EM_LINESCROLL,  "EM_LINESCROLL"},
	{EM_SCROLLCARET,  "EM_SCROLLCARET"},
	{EM_GETMODIFY,  "EM_GETMODIFY"},
	{EM_SETMODIFY,  "EM_SETMODIFY"},
	{EM_GETLINECOUNT,  "EM_GETLINECOUNT"},
	{EM_LINEINDEX,  "EM_LINEINDEX"},
	{EM_SETHANDLE,  "EM_SETHANDLE"},
	{EM_GETHANDLE,  "EM_GETHANDLE"},
	{EM_GETTHUMB,  "EM_GETTHUMB"},
	{EM_LINELENGTH,  "EM_LINELENGTH"},
	{EM_REPLACESEL,  "EM_REPLACESEL"},
	{EM_GETLINE,  "EM_GETLINE"},
	{EM_LIMITTEXT,  "EM_LIMITTEXT"},
	{EM_CANUNDO,  "EM_CANUNDO"},
	{EM_UNDO,  "EM_UNDO"},
	{EM_FMTLINES,  "EM_FMTLINES"},
	{EM_LINEFROMCHAR,  "EM_LINEFROMCHAR"},
	{EM_SETTABSTOPS,  "EM_SETTABSTOPS"},
	{EM_SETPASSWORDCHAR,  "EM_SETPASSWORDCHAR"},
	{EM_EMPTYUNDOBUFFER,  "EM_EMPTYUNDOBUFFER"},
	{EM_GETFIRSTVISIBLELINE,  "EM_GETFIRSTVISIBLELINE"},
	{EM_SETREADONLY,  "EM_SETREADONLY"},
	{EM_SETWORDBREAKPROC,  "EM_SETWORDBREAKPROC"},
	{EM_GETWORDBREAKPROC,  "EM_GETWORDBREAKPROC"},
	{EM_GETPASSWORDCHAR,  "EM_GETPASSWORDCHAR"},
	{EM_SETMARGINS,  "EM_SETMARGINS"},
	{EM_GETMARGINS,  "EM_GETMARGINS"},
	{EM_SETLIMITTEXT,  "EM_SETLIMITTEXT"},
	{EM_GETLIMITTEXT,  "EM_GETLIMITTEXT"},
	{EM_POSFROMCHAR,  "EM_POSFROMCHAR"},
	{EM_CHARFROMPOS,  "EM_CHARFROMPOS"},
	{EM_SETIMESTATUS,  "EM_SETIMESTATUS"},
	{EM_GETIMESTATUS,  "EM_GETIMESTATUS"},
	{NULL, NULL }
};




TValueString g_WindowPositionString[]=
{
	{SWP_NOSIZE,  "SWP_NOSIZE"},
	{SWP_NOMOVE,  "SWP_NOMOVE"},
	{SWP_NOZORDER,  "SWP_NOZORDER"},
	{SWP_NOREDRAW,  "SWP_NOREDRAW"},
	{SWP_NOACTIVATE,  "SWP_NOACTIVATE"},
	{SWP_FRAMECHANGED,  "SWP_FRAMECHANGED"},
	{SWP_SHOWWINDOW,  "SWP_SHOWWINDOW"},
	{SWP_HIDEWINDOW,  "SWP_HIDEWINDOW"},
	{SWP_NOCOPYBITS,  "SWP_NOCOPYBITS"},
	{SWP_NOOWNERZORDER,  "SWP_NOOWNERZORDER"},
	{SWP_NOSENDCHANGING,  "SWP_NOSENDCHANGING"},
	{SWP_DRAWFRAME,  "SWP_DRAWFRAME"},
	{SWP_NOREPOSITION,  "SWP_NOREPOSITION"},
	{SWP_DEFERERASE,  "SWP_DEFERERASE"},
	{SWP_ASYNCWINDOWPOS,  "SWP_ASYNCWINDOWPOS"},
	{NULL, NULL }
};

TValueString g_PrintClientString[]=
{
	{PRF_CHECKVISIBLE, "PRF_CHECKVISIBLE" },
	{PRF_NONCLIENT, "PRF_NONCLIENT" },
	{PRF_CLIENT, "PRF_CLIENT" },
	{PRF_ERASEBKGND, "PRF_ERASEBKGND" },
	{PRF_CHILDREN, "PRF_CHILDREN" },
	{PRF_OWNED, "PRF_OWNED" },
	{NULL, NULL },
};

TValueString g_OwnerDrawTypeString[]=
{
	{ODT_MENU,  "ODT_MENU"},
	{ODT_LISTBOX,  "ODT_LISTBOX"},
	{ODT_COMBOBOX,  "ODT_COMBOBOX"},
	{ODT_BUTTON,  "ODT_BUTTON"},
	{ODT_STATIC,  "ODT_STATIC"},
	{NULL, NULL }
};
TValueString g_OwnerDrawActionString[]=
{
	{ODA_DRAWENTIRE,  "ODA_DRAWENTIRE"},
	{ODA_SELECT,  "ODA_SELECT"},
	{ODA_FOCUS,  "ODA_FOCUS"},
	{NULL, NULL }
};
TValueString g_OwnerDrawStateString[]=
{
	{ODS_SELECTED,  "ODS_SELECTED"},
	{ODS_GRAYED,  "ODS_GRAYED"},
	{ODS_DISABLED,  "ODS_DISABLED"},
	{ODS_CHECKED,  "ODS_CHECKED"},
	{ODS_FOCUS,  "ODS_FOCUS"},
	{ODS_DEFAULT,  "ODS_DEFAULT"},
	{ODS_COMBOBOXEDIT,  "ODS_COMBOBOXEDIT"},
	{ODS_HOTLIGHT,  "ODS_HOTLIGHT"},
	{ODS_INACTIVE,  "ODS_INACTIVE"},
	{ODS_NOACCEL,  "ODS_NOACCEL"},
	{ODS_NOFOCUSRECT,  "ODS_NOFOCUSRECT"},

	{NULL, NULL }
};


TValueString g_DialogBoxCommandString[]=
{
	{IDOK,  "IDOK"},
	{IDCANCEL,  "IDCANCEL"},
	{IDABORT,  "IDABORT"},
	{IDRETRY,  "IDRETRY"},
	{IDIGNORE,  "IDIGNORE"},
	{IDYES,  "IDYES"},
	{IDNO,  "IDNO"},
	{IDCLOSE,  "IDCLOSE"},
	{IDHELP,  "IDHELP"},
	{IDTRYAGAIN,  "IDTRYAGAIN"},
	{IDCONTINUE,  "IDCONTINUE"},
	{IDTIMEOUT,  "IDTIMEOUT"},
};


TValueString g_ListBoxNotifyString[]=
{
	{LB_ADDFILE,  "LB_ADDFILE"},
	{LB_ADDSTRING,  "LB_ADDSTRING"},
	{LB_DELETESTRING,  "LB_DELETESTRING"},
	{LB_DIR,  "LB_DIR"},
	{LB_FINDSTRING,  "LB_FINDSTRING"},
	{LB_FINDSTRINGEXACT,  "LB_FINDSTRINGEXACT"},
	{LB_GETANCHORINDEX,  "LB_GETANCHORINDEX"},
	{LB_GETCARETINDEX,  "LB_GETCARETINDEX"},
	{LB_GETCOUNT,  "LB_GETCOUNT"},
	{LB_GETCURSEL,  "LB_GETCURSEL"},
	{LB_GETHORIZONTALEXTENT,  "LB_GETHORIZONTALEXTENT"},
	{LB_GETITEMDATA,  "LB_GETITEMDATA"},
	{LB_GETITEMHEIGHT,  "LB_GETITEMHEIGHT"},
	{LB_GETITEMRECT,  "LB_GETITEMRECT"},
	{LB_GETLISTBOXINFO,  "LB_GETLISTBOXINFO"},
	{LB_GETLOCALE,  "LB_GETLOCALE"},
	{LB_GETSEL,  "LB_GETSEL"},
	{LB_GETSELCOUNT,  "LB_GETSELCOUNT"},
	{LB_GETSELITEMS,  "LB_GETSELITEMS"},
	{LB_GETTEXT,  "LB_GETTEXT"},
	{LB_GETTEXTLEN,  "LB_GETTEXTLEN"},
	{LB_GETTOPINDEX,  "LB_GETTOPINDEX"},
	{LB_INITSTORAGE,  "LB_INITSTORAGE"},
	{LB_INSERTSTRING,  "LB_INSERTSTRING"},
	{LB_ITEMFROMPOINT,  "LB_ITEMFROMPOINT"},
	{LB_RESETCONTENT,  "LB_RESETCONTENT"},
	{LB_SELECTSTRING,  "LB_SELECTSTRING"},
	{LB_SELITEMRANGE,  "LB_SELITEMRANGE"},
	{LB_SELITEMRANGEEX,  "LB_SELITEMRANGEEX"},
	{LB_SETANCHORINDEX,  "LB_SETANCHORINDEX"},
	{LB_SETCARETINDEX,  "LB_SETCARETINDEX"},
	{LB_SETCOLUMNWIDTH,  "LB_SETCOLUMNWIDTH"},
	{LB_SETCOUNT,  "LB_SETCOUNT"},
	{LB_SETCURSEL,  "LB_SETCURSEL"},
	{LB_SETHORIZONTALEXTENT,  "LB_SETHORIZONTALEXTENT"},
	{LB_SETITEMDATA,  "LB_SETITEMDATA"},
	{LB_SETITEMHEIGHT,  "LB_SETITEMHEIGHT"},
	{LB_SETLOCALE,  "LB_SETLOCALE"},
	{LB_SETSEL,  "LB_SETSEL"},
	{LB_SETTABSTOPS,  "LB_SETTABSTOPS"},
	{LB_SETTOPINDEX,  "LB_SETTOPINDEX"},
	{NULL, NULL }
};
TValueString g_WmNotifyGenericString[]=
{
	{NM_OUTOFMEMORY,  "NM_OUTOFMEMORY"},
	{NM_CLICK,  "NM_CLICK"},
	{NM_DBLCLK,  "NM_DBLCLK"},
	{NM_RETURN,  "NM_RETURN"},
	{NM_RCLICK,  "NM_RCLICK"},
	{NM_RDBLCLK,  "NM_RDBLCLK"},
	{NM_SETFOCUS,  "NM_SETFOCUS"},
	{NM_KILLFOCUS,  "NM_KILLFOCUS"},
	{NM_CUSTOMDRAW,  "NM_CUSTOMDRAW"},
	{NM_HOVER,  "NM_HOVER"},
	{NM_NCHITTEST,  "NM_NCHITTEST"},
	{NM_KEYDOWN,  "NM_KEYDOWN"},
	{NM_RELEASEDCAPTURE,  "NM_RELEASEDCAPTURE"},
	{NM_SETCURSOR,  "NM_SETCURSOR"},
	{NM_CHAR,  "NM_CHAR"},
	{NM_TOOLTIPSCREATED,  "NM_TOOLTIPSCREATED"},
	{NM_LDOWN,  "NM_LDOWN"},
	{NM_RDOWN,  "NM_RDOWN"},
	{NM_THEMECHANGED,  "NM_THEMECHANGED"},
	{NM_FONTCHANGED,  "NM_FONTCHANGED"},
	{NM_CUSTOMTEXT,  "NM_CUSTOMTEXT"},
	{NM_TVSTATEIMAGECHANGING,  "NM_TVSTATEIMAGECHANGING"},
	{NULL, NULL }
};
TValueString g_HeaderControlNotifyString[]=
{
	{HDN_ITEMCHANGINGA,  "HDN_ITEMCHANGINGA"},
	{HDN_ITEMCHANGINGW,  "HDN_ITEMCHANGINGW"},
	{HDN_ITEMCHANGEDA,  "HDN_ITEMCHANGEDA"},
	{HDN_ITEMCHANGEDW,  "HDN_ITEMCHANGEDW"},
	{HDN_ITEMCLICKA,  "HDN_ITEMCLICKA"},
	{HDN_ITEMCLICKW,  "HDN_ITEMCLICKW"},
	{HDN_ITEMDBLCLICKA,  "HDN_ITEMDBLCLICKA"},
	{HDN_ITEMDBLCLICKW,  "HDN_ITEMDBLCLICKW"},
	{HDN_DIVIDERDBLCLICKA,  "HDN_DIVIDERDBLCLICKA"},
	{HDN_DIVIDERDBLCLICKW,  "HDN_DIVIDERDBLCLICKW"},
	{HDN_BEGINTRACKA,  "HDN_BEGINTRACKA"},
	{HDN_BEGINTRACKW,  "HDN_BEGINTRACKW"},
	{HDN_ENDTRACKA,  "HDN_ENDTRACKA"},
	{HDN_ENDTRACKW,  "HDN_ENDTRACKW"},
	{HDN_TRACKA,  "HDN_TRACKA"},
	{HDN_TRACKW,  "HDN_TRACKW"},
	{HDN_GETDISPINFOA,  "HDN_GETDISPINFOA"},
	{HDN_GETDISPINFOW,  "HDN_GETDISPINFOW"},
	{HDN_BEGINDRAG,  "HDN_BEGINDRAG"},
	{HDN_ENDDRAG,  "HDN_ENDDRAG"},
	{HDN_FILTERCHANGE,  "HDN_FILTERCHANGE"},
	{HDN_FILTERBTNCLICK,  "HDN_FILTERBTNCLICK"},
	{HDN_BEGINFILTEREDIT,  "HDN_BEGINFILTEREDIT"},
	{HDN_ENDFILTEREDIT,  "HDN_ENDFILTEREDIT"},
	{HDN_ITEMSTATEICONCLICK,  "HDN_ITEMSTATEICONCLICK"},
	{HDN_ITEMKEYDOWN,  "HDN_ITEMKEYDOWN"},
	{HDN_DROPDOWN,  "HDN_DROPDOWN"},
	{HDN_OVERFLOWCLICK,  "HDN_OVERFLOWCLICK"},
	{NULL, NULL }
};
TValueString g_ListViewNotifyString[]=
{
	{LVN_BEGINDRAG, "LVN_BEGINDRAG"},
	{LVN_BEGINLABELEDIT, "LVN_BEGINLABELEDIT"},
	{LVN_BEGINRDRAG, "LVN_BEGINRDRAG"},
	{LVN_BEGINSCROLL, "LVN_BEGINSCROLL"},
	{LVN_COLUMNCLICK, "LVN_COLUMNCLICK"},
	{LVN_COLUMNDROPDOWN, "LVN_COLUMNDROPDOWN"},
	{LVN_COLUMNOVERFLOWCLICK, "LVN_COLUMNOVERFLOWCLICK"},
	{LVN_DELETEALLITEMS, "LVN_DELETEALLITEMS"},
	{LVN_DELETEITEM, "LVN_DELETEITEM"},
	{LVN_ENDLABELEDIT, "LVN_ENDLABELEDIT"},
	{LVN_ENDSCROLL, "LVN_ENDSCROLL"},
	{LVN_GETDISPINFO, "LVN_GETDISPINFO"},
	{LVN_GETEMPTYMARKUP, "LVN_GETEMPTYMARKUP"},
	{LVN_GETINFOTIP, "LVN_GETINFOTIP"},
	{LVN_HOTTRACK, "LVN_HOTTRACK"},
	{LVN_INCREMENTALSEARCH, "LVN_INCREMENTALSEARCH"},
	{LVN_INSERTITEM, "LVN_INSERTITEM"},
	{LVN_ITEMACTIVATE, "LVN_ITEMACTIVATE"},
	{LVN_ITEMCHANGED, "LVN_ITEMCHANGED"},
	{LVN_ITEMCHANGING, "LVN_ITEMCHANGING"},
	{LVN_KEYDOWN, "LVN_KEYDOWN"},
	{LVN_LINKCLICK, "LVN_LINKCLICK"},
	{LVN_MARQUEEBEGIN, "LVN_MARQUEEBEGIN"},
	{LVN_ODCACHEHINT, "LVN_ODCACHEHINT"},
	{LVN_ODFINDITEM, "LVN_ODFINDITEM"},
	{LVN_ODSTATECHANGED, "LVN_ODSTATECHANGED"},
	{LVN_SETDISPINFO, "LVN_SETDISPINFO"},
	{NM_CLICK, "NM_CLICK"},
	{NM_DBLCLK , "NM_DBLCLK "},
	{NM_HOVER, "NM_HOVER"},
	{NM_KILLFOCUS, "NM_KILLFOCUS"},
	{NM_RCLICK, "NM_RCLICK"},
	{NM_RDBLCLK, "NM_RDBLCLK"},
	{NM_RELEASEDCAPTURE, "NM_RELEASEDCAPTURE"},
	{NM_RETURN, "NM_RETURN"},
	{NM_SETFOCUS, "NM_SETFOCUS"}
	
};

TValueString g_TreeViewItemStateString[]=
{
	{TVIF_STATEEX,  "TVIF_STATEEX"},
	{TVIF_EXPANDEDIMAGE,  "TVIF_EXPANDEDIMAGE"},
	{TVIS_SELECTED,  "TVIS_SELECTED"},
	{TVIS_CUT,  "TVIS_CUT"},
	{TVIS_DROPHILITED,  "TVIS_DROPHILITED"},
	{TVIS_BOLD,  "TVIS_BOLD"},
	{TVIS_EXPANDED,  "TVIS_EXPANDED"},
	{TVIS_EXPANDEDONCE,  "TVIS_EXPANDEDONCE"},
	{TVIS_EXPANDPARTIAL,  "TVIS_EXPANDPARTIAL"},
	{TVIS_OVERLAYMASK,  "TVIS_OVERLAYMASK"},
	{TVIS_STATEIMAGEMASK,  "TVIS_STATEIMAGEMASK"},
	{TVIS_USERMASK,  "TVIS_USERMASK"},
	{TVIS_EX_DISABLED,  "TVIS_EX_DISABLED"},
	{TVIS_EX_ALL,  "TVIS_EX_ALL"},
	{NULL, NULL }
};


TValueString g_TreeViewMessageString[]=
{
	{TVM_CREATEDRAGIMAGE,  "TVM_CREATEDRAGIMAGE"},
	{TVM_DELETEITEM,  "TVM_DELETEITEM"},
	{TVM_EDITLABEL,  "TVM_EDITLABEL"},
	{TVM_ENDEDITLABELNOW,  "TVM_ENDEDITLABELNOW"},
	{TVM_ENSUREVISIBLE,  "TVM_ENSUREVISIBLE"},
	{TVM_EXPAND,  "TVM_EXPAND"},
	{TVM_GETBKCOLOR,  "TVM_GETBKCOLOR"},
	{TVM_GETCOUNT,  "TVM_GETCOUNT"},
	{TVM_GETEDITCONTROL,  "TVM_GETEDITCONTROL"},
	{TVM_GETEXTENDEDSTYLE,  "TVM_GETEXTENDEDSTYLE"},
	{TVM_GETIMAGELIST,  "TVM_GETIMAGELIST"},
	{TVM_GETINDENT,  "TVM_GETINDENT"},
	{TVM_GETINSERTMARKCOLOR,  "TVM_GETINSERTMARKCOLOR"},
	{TVM_GETISEARCHSTRING,  "TVM_GETISEARCHSTRING"},
	{TVM_GETITEM,  "TVM_GETITEM"},
	{TVM_GETITEMHEIGHT,  "TVM_GETITEMHEIGHT"},
	{TVM_GETITEMPARTRECT,  "TVM_GETITEMPARTRECT"},
	{TVM_GETITEMRECT,  "TVM_GETITEMRECT"},
	{TVM_GETITEMSTATE,  "TVM_GETITEMSTATE"},
	{TVM_GETLINECOLOR,  "TVM_GETLINECOLOR"},
	{TVM_GETNEXTITEM,  "TVM_GETNEXTITEM"},
	{TVM_GETSCROLLTIME,  "TVM_GETSCROLLTIME"},
	{TVM_GETSELECTEDCOUNT,  "TVM_GETSELECTEDCOUNT"},
	{TVM_GETTEXTCOLOR,  "TVM_GETTEXTCOLOR"},
	{TVM_GETTOOLTIPS,  "TVM_GETTOOLTIPS"},
	{TVM_GETUNICODEFORMAT,  "TVM_GETUNICODEFORMAT"},
	{TVM_GETVISIBLECOUNT,  "TVM_GETVISIBLECOUNT"},
	{TVM_HITTEST,  "TVM_HITTEST"},
	{TVM_INSERTITEM,  "TVM_INSERTITEM"},
	{TVM_MAPACCIDTOHTREEITEM,  "TVM_MAPACCIDTOHTREEITEM"},
	{TVM_MAPHTREEITEMTOACCID,  "TVM_MAPHTREEITEMTOACCID"},
	{TVM_SELECTITEM,  "TVM_SELECTITEM"},
	{TVM_SETAUTOSCROLLINFO,  "TVM_SETAUTOSCROLLINFO"},
	{TVM_SETBKCOLOR,  "TVM_SETBKCOLOR"},
	//{TVM_SETBORDER,  "TVM_SETBORDER"},
	{TVM_SETEXTENDEDSTYLE,  "TVM_SETEXTENDEDSTYLE"},
	//{TVM_SETHOT,  "TVM_SETHOT"},
	{TVM_SETIMAGELIST,  "TVM_SETIMAGELIST"},
	{TVM_SETINDENT,  "TVM_SETINDENT"},
	{TVM_SETINSERTMARK,  "TVM_SETINSERTMARK"},
	{TVM_SETINSERTMARKCOLOR,  "TVM_SETINSERTMARKCOLOR"},
	{TVM_SETITEM,  "TVM_SETITEM"},
	{TVM_SETITEMHEIGHT,  "TVM_SETITEMHEIGHT"},
	{TVM_SETLINECOLOR,  "TVM_SETLINECOLOR"},
	{TVM_SETSCROLLTIME,  "TVM_SETSCROLLTIME"},
	{TVM_SETTEXTCOLOR,  "TVM_SETTEXTCOLOR"},
	{TVM_SETTOOLTIPS,  "TVM_SETTOOLTIPS"},
	{TVM_SETUNICODEFORMAT,  "TVM_SETUNICODEFORMAT"},
	{TVM_SHOWINFOTIP,  "TVM_SHOWINFOTIP"},
	{TVM_SORTCHILDREN,  "TVM_SORTCHILDREN"},
	{TVM_SORTCHILDRENCB,  "TVM_SORTCHILDRENCB"},
};

TValueString g_TreeViewNotifyString[]={
	{NM_CLICK,  "NM_CLICK"},
	{NM_CUSTOMDRAW,  "NM_CUSTOMDRAW"},
	{NM_DBLCLK,  "NM_DBLCLK"},
	{NM_KILLFOCUS,  "NM_KILLFOCUS"},
	{NM_RCLICK,  "NM_RCLICK"},
	{NM_RDBLCLK,  "NM_RDBLCLK"},
	{NM_RETURN,  "NM_RETURN"},
	{NM_SETCURSOR,  "NM_SETCURSOR"},
	{NM_SETFOCUS,  "NM_SETFOCUS"},
	{TVN_ASYNCDRAW,  "TVN_ASYNCDRAW"},
	{TVN_BEGINDRAG,  "TVN_BEGINDRAG"},
	{TVN_BEGINLABELEDIT,  "TVN_BEGINLABELEDIT"},
	{TVN_BEGINRDRAG,  "TVN_BEGINRDRAG"},
	{TVN_DELETEITEM,  "TVN_DELETEITEM"},
	{TVN_ENDLABELEDIT,  "TVN_ENDLABELEDIT"},
	{TVN_GETDISPINFO,  "TVN_GETDISPINFO"},
	{TVN_GETINFOTIP,  "TVN_GETINFOTIP"},
	{TVN_ITEMCHANGED,  "TVN_ITEMCHANGED"},
	{TVN_ITEMCHANGING,  "TVN_ITEMCHANGING"},
	{TVN_ITEMEXPANDED,  "TVN_ITEMEXPANDED"},
	{TVN_ITEMEXPANDING,  "TVN_ITEMEXPANDING"},
	{TVN_KEYDOWN,  "TVN_KEYDOWN"},
	{TVN_SELCHANGED,  "TVN_SELCHANGED"},
	{TVN_SELCHANGING,  "TVN_SELCHANGING"},
	{TVN_SETDISPINFO,  "TVN_SETDISPINFO"},
	{TVN_SINGLEEXPAND,  "TVN_SINGLEEXPAND"},
	{TTN_GETDISPINFO, "TTN_GETDISPINFO"},
};

TValueString g_ComboBoxMessageString[]=
{
	{CB_GETEDITSEL,  "CB_GETEDITSEL"},
	{CB_LIMITTEXT,  "CB_LIMITTEXT"},
	{CB_SETEDITSEL,  "CB_SETEDITSEL"},
	{CB_ADDSTRING,  "CB_ADDSTRING"},
	{CB_DELETESTRING,  "CB_DELETESTRING"},
	{CB_DIR,  "CB_DIR"},
	{CB_GETCOUNT,  "CB_GETCOUNT"},
	{CB_GETCURSEL,  "CB_GETCURSEL"},
	{CB_GETLBTEXT,  "CB_GETLBTEXT"},
	{CB_GETLBTEXTLEN,  "CB_GETLBTEXTLEN"},
	{CB_INSERTSTRING,  "CB_INSERTSTRING"},
	{CB_RESETCONTENT,  "CB_RESETCONTENT"},
	{CB_FINDSTRING,  "CB_FINDSTRING"},
	{CB_SELECTSTRING,  "CB_SELECTSTRING"},
	{CB_SETCURSEL,  "CB_SETCURSEL"},
	{CB_SHOWDROPDOWN,  "CB_SHOWDROPDOWN"},
	{CB_GETITEMDATA,  "CB_GETITEMDATA"},
	{CB_SETITEMDATA,  "CB_SETITEMDATA"},
	{CB_GETDROPPEDCONTROLRECT,  "CB_GETDROPPEDCONTROLRECT"},
	{CB_SETITEMHEIGHT,  "CB_SETITEMHEIGHT"},
	{CB_GETITEMHEIGHT,  "CB_GETITEMHEIGHT"},
	{CB_SETEXTENDEDUI,  "CB_SETEXTENDEDUI"},
	{CB_GETEXTENDEDUI,  "CB_GETEXTENDEDUI"},
	{CB_GETDROPPEDSTATE,  "CB_GETDROPPEDSTATE"},
	{CB_FINDSTRINGEXACT,  "CB_FINDSTRINGEXACT"},
	{CB_SETLOCALE,  "CB_SETLOCALE"},
	{CB_GETLOCALE,  "CB_GETLOCALE"},
	{CB_GETTOPINDEX,  "CB_GETTOPINDEX"},
	{CB_SETTOPINDEX,  "CB_SETTOPINDEX"},
	{CB_GETHORIZONTALEXTENT,  "CB_GETHORIZONTALEXTENT"},
	{CB_SETHORIZONTALEXTENT,  "CB_SETHORIZONTALEXTENT"},
	{CB_GETDROPPEDWIDTH,  "CB_GETDROPPEDWIDTH"},
	{CB_SETDROPPEDWIDTH,  "CB_SETDROPPEDWIDTH"},
	{CB_INITSTORAGE,  "CB_INITSTORAGE"},
	//{CB_MULTIPLEADDSTRING,  "CB_MULTIPLEADDSTRING"},
	{CB_GETCOMBOBOXINFO,  "CB_GETCOMBOBOXINFO"},
	{CB_MSGMAX,  "CB_MSGMAX"},
	{CB_MSGMAX,  "CB_MSGMAX"},
	{CB_MSGMAX,  "CB_MSGMAX"},
	{CB_MSGMAX,  "CB_MSGMAX"},
};

TValueString g_ComboBoxNotifyString[]=
{
	{CBN_ERRSPACE,  "CBN_ERRSPACE"},
	{CBN_SELCHANGE,  "CBN_SELCHANGE"},
	{CBN_DBLCLK,  "CBN_DBLCLK"},
	{CBN_SETFOCUS,  "CBN_SETFOCUS"},
	{CBN_KILLFOCUS,  "CBN_KILLFOCUS"},
	{CBN_EDITCHANGE,  "CBN_EDITCHANGE"},
	{CBN_EDITUPDATE,  "CBN_EDITUPDATE"},
	{CBN_DROPDOWN,  "CBN_DROPDOWN"},
	{CBN_CLOSEUP,  "CBN_CLOSEUP"},
	{CBN_SELENDOK,  "CBN_SELENDOK"},
	{CBN_SELENDCANCEL,  "CBN_SELENDCANCEL"},
};


TValueString g_EditNotifyString[]=
{
	{EN_SETFOCUS,  "EN_SETFOCUS"},
	{EN_KILLFOCUS,  "EN_KILLFOCUS"},
	{EN_CHANGE,  "EN_CHANGE"},
	{EN_UPDATE,  "EN_UPDATE"},
	{EN_ERRSPACE,  "EN_ERRSPACE"},
	{EN_MAXTEXT,  "EN_MAXTEXT"},
	{EN_HSCROLL,  "EN_HSCROLL"},
	{EN_VSCROLL,  "EN_VSCROLL"},
	{EN_ALIGN_LTR_EC,  "EN_ALIGN_LTR_EC"},
	{EN_ALIGN_RTL_EC,  "EN_ALIGN_RTL_EC"},
	{EC_LEFTMARGIN,  "EC_LEFTMARGIN"},
	{EC_RIGHTMARGIN,  "EC_RIGHTMARGIN"},
	{EC_USEFONTINFO,  "EC_USEFONTINFO"},
	{EMSIS_COMPOSITIONSTRING,  "EMSIS_COMPOSITIONSTRING"},
	{EIMES_GETCOMPSTRATONCE,  "EIMES_GETCOMPSTRATONCE"},
	{EIMES_CANCELCOMPSTRINFOCUS,  "EIMES_CANCELCOMPSTRINFOCUS"},
	{EIMES_COMPLETECOMPSTRKILLFOCUS,  "EIMES_COMPLETECOMPSTRKILLFOCUS"},
};



TValueString g_CustomDrawStageString[]=
{
	{CDDS_PREPAINT,  "CDDS_PREPAINT"},
	{CDDS_POSTPAINT,  "CDDS_POSTPAINT"},
	{CDDS_PREERASE,  "CDDS_PREERASE"},
	{CDDS_POSTERASE,  "CDDS_POSTERASE"},
	{CDDS_ITEMPREPAINT,  "CDDS_ITEMPREPAINT"},
	{CDDS_ITEMPOSTPAINT,  "CDDS_ITEMPOSTPAINT"},
	{CDDS_ITEMPREERASE,  "CDDS_ITEMPREERASE"},
	{CDDS_ITEMPOSTERASE,  "CDDS_ITEMPOSTERASE"},
	{CDDS_SUBITEM,  "CDDS_SUBITEM"},
	{0, NULL}
};
TValueString g_CustomDrawItemStateString[]=
{
	{CDIS_SELECTED,  "CDIS_SELECTED"},
	{CDIS_GRAYED,  "CDIS_GRAYED"},
	{CDIS_DISABLED,  "CDIS_DISABLED"},
	{CDIS_CHECKED,  "CDIS_CHECKED"},
	{CDIS_FOCUS,  "CDIS_FOCUS"},
	{CDIS_DEFAULT,  "CDIS_DEFAULT"},
	{CDIS_HOT,  "CDIS_HOT"},
	{CDIS_MARKED,  "CDIS_MARKED"},
	{CDIS_INDETERMINATE,  "CDIS_INDETERMINATE"},
	{CDIS_SHOWKEYBOARDCUES,  "CDIS_SHOWKEYBOARDCUES"},
	{CDIS_NEARHOT,  "CDIS_NEARHOT"},
	{CDIS_OTHERSIDEHOT,  "CDIS_OTHERSIDEHOT"},
	{CDIS_DROPHILITED,  "CDIS_DROPHILITED"},
	{NULL, NULL }
};
TValueString g_VmSizeTypeString[]=
{
	{SIZE_RESTORED,  "SIZE_RESTORED"},
	{SIZE_MINIMIZED,  "SIZE_MINIMIZED"},
	{SIZE_MAXIMIZED,  "SIZE_MAXIMIZED"},
	{SIZE_MAXSHOW,  "SIZE_MAXSHOW"},
	{SIZE_MAXHIDE,  "SIZE_MAXHIDE"},
	{NULL, NULL }
};

TValueString g_VmPrintClientString[]=
{
	{PRF_CHECKVISIBLE,  "PRF_CHECKVISIBLE"},
	{PRF_NONCLIENT,  "PRF_NONCLIENT"},
	{PRF_CLIENT,  "PRF_CLIENT"},
	{PRF_CHILDREN,  "PRF_CHILDREN"},
	{PRF_OWNED,  "PRF_OWNED"},
	{0, NULL}
};
TValueString g_ListBoxMessageString[]=
{
	{LB_ADDSTRING,  "LB_ADDSTRING"},
	{LB_INSERTSTRING,  "LB_INSERTSTRING"},
	{LB_DELETESTRING,  "LB_DELETESTRING"},
	{LB_SELITEMRANGEEX,  "LB_SELITEMRANGEEX"},
	{LB_RESETCONTENT,  "LB_RESETCONTENT"},
	{LB_SETSEL,  "LB_SETSEL"},
	{LB_SETCURSEL,  "LB_SETCURSEL"},
	{LB_GETSEL,  "LB_GETSEL"},
	{LB_GETCURSEL,  "LB_GETCURSEL"},
	{LB_GETTEXT,  "LB_GETTEXT"},
	{LB_GETTEXTLEN,  "LB_GETTEXTLEN"},
	{LB_GETCOUNT,  "LB_GETCOUNT"},
	{LB_SELECTSTRING,  "LB_SELECTSTRING"},
	{LB_DIR,  "LB_DIR"},
	{LB_GETTOPINDEX,  "LB_GETTOPINDEX"},
	{LB_FINDSTRING,  "LB_FINDSTRING"},
	{LB_GETSELCOUNT,  "LB_GETSELCOUNT"},
	{LB_GETSELITEMS,  "LB_GETSELITEMS"},
	{LB_SETTABSTOPS,  "LB_SETTABSTOPS"},
	{LB_GETHORIZONTALEXTENT,  "LB_GETHORIZONTALEXTENT"},
	{LB_SETHORIZONTALEXTENT,  "LB_SETHORIZONTALEXTENT"},
	{LB_SETCOLUMNWIDTH,  "LB_SETCOLUMNWIDTH"},
	{LB_ADDFILE,  "LB_ADDFILE"},
	{LB_SETTOPINDEX,  "LB_SETTOPINDEX"},
	{LB_GETITEMRECT,  "LB_GETITEMRECT"},
	{LB_GETITEMDATA,  "LB_GETITEMDATA"},
	{LB_SETITEMDATA,  "LB_SETITEMDATA"},
	{LB_SELITEMRANGE,  "LB_SELITEMRANGE"},
	{LB_SETANCHORINDEX,  "LB_SETANCHORINDEX"},
	{LB_GETANCHORINDEX,  "LB_GETANCHORINDEX"},
	{LB_SETCARETINDEX,  "LB_SETCARETINDEX"},
	{LB_GETCARETINDEX,  "LB_GETCARETINDEX"},
	{LB_SETITEMHEIGHT,  "LB_SETITEMHEIGHT"},
	{LB_GETITEMHEIGHT,  "LB_GETITEMHEIGHT"},
	{LB_FINDSTRINGEXACT,  "LB_FINDSTRINGEXACT"},
	{LB_SETLOCALE,  "LB_SETLOCALE"},
	{LB_GETLOCALE,  "LB_GETLOCALE"},
	{LB_SETCOUNT,  "LB_SETCOUNT"},
	{LB_INITSTORAGE,  "LB_INITSTORAGE"},
	{LB_ITEMFROMPOINT,  "LB_ITEMFROMPOINT"},

	{0x1B1,  "LB_MULTIPLEADDSTRING"},
	{LB_GETLISTBOXINFO,  "LB_GETLISTBOXINFO"},
	{LB_MSGMAX,  "LB_MSGMAX"},
	{LB_MSGMAX,  "LB_MSGMAX"},
	{LB_MSGMAX,  "LB_MSGMAX"},
	{LB_MSGMAX,  "LB_MSGMAX"},
	{NULL, NULL }
};

TValueString g_NCHitTestRetString[]=
{
	{HTERROR,  "HTERROR"},
	{HTTRANSPARENT,  "HTTRANSPARENT"},
	{HTNOWHERE,  "HTNOWHERE"},
	{HTCLIENT,  "HTCLIENT"},
	{HTCAPTION,  "HTCAPTION"},
	{HTSYSMENU,  "HTSYSMENU"},
	{HTGROWBOX,  "HTGROWBOX/HTSIZE"},
	{HTMENU,  "HTMENU"},
	{HTHSCROLL,  "HTHSCROLL"},
	{HTVSCROLL,  "HTVSCROLL"},
	{HTMINBUTTON,  "HTMINBUTTON/HTREDUCE"},
	{HTMAXBUTTON,  "HTMAXBUTTON/HTZOOM"},
	{HTLEFT,  "HTLEFT/HTSIZEFIRST"},
	{HTRIGHT,  "HTRIGHT/HTSIZELAST"},
	{HTTOP,  "HTTOP"},
	{HTTOPLEFT,  "HTTOPLEFT"},
	{HTTOPRIGHT,  "HTTOPRIGHT"},
	{HTBOTTOM,  "HTBOTTOM"},
	{HTBOTTOMLEFT,  "HTBOTTOMLEFT"},
	{HTBOTTOMRIGHT,  "HTBOTTOMRIGHT"},
	{HTBORDER,  "HTBORDER"},
	{HTOBJECT,  "HTOBJECT"},
	{HTCLOSE,  "HTCLOSE"},
	{HTHELP,  "HTHELP"},
	{NULL, NULL }
};

TValueString g_VmIMESetContextString[]=
{
	{ISC_SHOWUICANDIDATEWINDOW,  "ISC_SHOWUICANDIDATEWINDOW"},
	{ISC_SHOWUICOMPOSITIONWINDOW,  "ISC_SHOWUICOMPOSITIONWINDOW"},
	{ISC_SHOWUIGUIDELINE,  "ISC_SHOWUIGUIDELINE"},
	{ISC_SHOWUIALLCANDIDATEWINDOW,  "ISC_SHOWUIALLCANDIDATEWINDOW"},
	{ISC_SHOWUIALL,  "ISC_SHOWUIALL"},
	{0, NULL}
};

TValueString g_ButtonNotifyString[]=
{
	{BCN_DROPDOWN,  "BCN_DROPDOWN"},
	{BCN_HOTITEMCHANGE,  "BCN_HOTITEMCHANGE"},
	{BN_CLICKED,  "BN_CLICKED"},
	{BN_DBLCLK,  "BN_DBLCLK"},
	{BN_DISABLE,  "BN_DISABLE"},
	{BN_DOUBLECLICKED,  "BN_DOUBLECLICKED"},
	{BN_HILITE,  "BN_HILITE"},
	{BN_KILLFOCUS,  "BN_KILLFOCUS"},
	{BN_PAINT,  "BN_PAINT"},
	{BN_PUSHED,  "BN_PUSHED"},
	{BN_SETFOCUS,  "BN_SETFOCUS"},
	{BN_UNHILITE,  "BN_UNHILITE"},
	{BN_UNPUSHED,  "BN_UNPUSHED"},
	{NM_CUSTOMDRAW,  "NM_CUSTOMDRAW"},
	{WM_CTLCOLORBTN,  "WM_CTLCOLORBTN"},
	{NULL, NULL }
};

TValueString g_ScrollBarMessageString[]=
{
	{ 0, "SB_LINEUP         " },
	{ 0, "SB_LINELEFT       " },
	{ 1, "SB_LINEDOWN       " },
	{ 1, "SB_LINERIGHT      " },
	{ 2, "SB_PAGEUP         " },
	{ 2, "SB_PAGELEFT       " },
	{ 3, "SB_PAGEDOWN       " },
	{ 3, "SB_PAGERIGHT      " },
	{ 4, "SB_THUMBPOSITION  " },
	{ 5, "SB_THUMBTRACK     " },
	{ 6, "SB_TOP            " },
	{ 6, "SB_LEFT           " },
	{ 7, "SB_BOTTOM         " },
	{ 7, "SB_RIGHT          " },
	{ 8, "SB_ENDSCROLL      " },
};
TValueString g_HeaderNotifyValueString[]=
{
	{HDN_BEGINDRAG,  "HDN_BEGINDRAG"},
	{HDN_BEGINFILTEREDIT,  "HDN_BEGINFILTEREDIT"},
	{HDN_BEGINTRACK,  "HDN_BEGINTRACK"},
	{HDN_DIVIDERDBLCLICK,  "HDN_DIVIDERDBLCLICK"},
	{HDN_DROPDOWN,  "HDN_DROPDOWN"},
	{HDN_ENDDRAG,  "HDN_ENDDRAG"},
	{HDN_ENDFILTEREDIT,  "HDN_ENDFILTEREDIT"},
	{HDN_FILTERBTNCLICK,  "HDN_FILTERBTNCLICK"},
	{HDN_FILTERCHANGE,  "HDN_FILTERCHANGE"},
	{HDN_GETDISPINFO,  "HDN_GETDISPINFO"},
	{HDN_ITEMCHANGED,  "HDN_ITEMCHANGED"},
	{HDN_ITEMCHANGING,  "HDN_ITEMCHANGING"},
	{HDN_ITEMCLICK,  "HDN_ITEMCLICK"},
	{HDN_ITEMDBLCLICK,  "HDN_ITEMDBLCLICK"},
	{HDN_ITEMKEYDOWN,  "HDN_ITEMKEYDOWN"},
	{HDN_ITEMSTATEICONCLICK,  "HDN_ITEMSTATEICONCLICK"},
	{HDN_OVERFLOWCLICK,  "HDN_OVERFLOWCLICK"},
	{HDN_TRACK,  "HDN_TRACK"},
	{NM_CUSTOMDRAW,  "NM_CUSTOMDRAW"},
	{NM_RCLICK,  "NM_RCLICK"},
	{NM_RELEASEDCAPTURE,  "NM_RELEASEDCAPTURE"},
	{NULL, NULL }
};

TValueString g_TabCtrlNotifyValueString[]=
{
	{NM_CLICK ,  "NM_CLICK"},
	{NM_DBLCLK ,  "NM_DBLCLK"},
	{NM_RCLICK ,  "NM_RCLICK"},
	{NM_RDBLCLK ,  "NM_RDBLCLK"},
	{NM_RELEASEDCAPTURE ,  "NM_RELEASEDCAPTURE "},
	{TCN_FOCUSCHANGE,  "TCN_FOCUSCHANGE"},
	{TCN_GETOBJECT,  "TCN_GETOBJECT"},
	{TCN_KEYDOWN,  "TCN_KEYDOWN"},
	{TCN_SELCHANGE,  "TCN_SELCHANGE"},
	{TCN_SELCHANGING,  "TCN_SELCHANGING"},
	{NULL, NULL }
};

TValueString g_ToolTipCtrlNotifyValueString[]=
{
	{NM_CUSTOMDRAW  ,  "NM_CUSTOMDRAW "},
	{TTN_GETDISPINFO ,  "TTN_GETDISPINFO"},
	{TTN_LINKCLICK ,  "TTN_LINKCLICK"},
	{TTN_NEEDTEXT ,  "TTN_NEEDTEXT"},
	{TTN_POP ,  "TTN_POP "},
	{TTN_SHOW,  "TTN_SHOW"},
	{NULL, NULL }
};




TValueString g_VirtualKeyString[]=
{
	{VK_LBUTTON,  "VK_LBUTTON"},
	{VK_RBUTTON,  "VK_RBUTTON"},
	{VK_CANCEL,  "VK_CANCEL"},
	{VK_MBUTTON,  "VK_MBUTTON"},
	{VK_XBUTTON1,  "VK_XBUTTON1"},
	{VK_XBUTTON2,  "VK_XBUTTON2"},
	{VK_BACK,  "VK_BACK"},
	{VK_TAB,  "VK_TAB"},
	{VK_CLEAR,  "VK_CLEAR"},
	{VK_RETURN,  "VK_RETURN"},
	{VK_SHIFT,  "VK_SHIFT"},
	{VK_CONTROL,  "VK_CONTROL"},
	{VK_MENU,  "VK_MENU"},
	{VK_PAUSE,  "VK_PAUSE"},
	{VK_CAPITAL,  "VK_CAPITAL"},
	{VK_KANA,  "VK_KANA"},
	{VK_HANGEUL,  "VK_HANGEUL"},
	{VK_HANGUL,  "VK_HANGUL"},
	{VK_JUNJA,  "VK_JUNJA"},
	{VK_FINAL,  "VK_FINAL"},
	{VK_HANJA,  "VK_HANJA"},
	{VK_KANJI,  "VK_KANJI"},
	{VK_ESCAPE,  "VK_ESCAPE"},
	{VK_CONVERT,  "VK_CONVERT"},
	{VK_NONCONVERT,  "VK_NONCONVERT"},
	{VK_ACCEPT,  "VK_ACCEPT"},
	{VK_MODECHANGE,  "VK_MODECHANGE"},
	{VK_SPACE,  "VK_SPACE"},
	{VK_PRIOR,  "VK_PRIOR"},
	{VK_NEXT,  "VK_NEXT"},
	{VK_END,  "VK_END"},
	{VK_HOME,  "VK_HOME"},
	{VK_LEFT,  "VK_LEFT"},
	{VK_UP,  "VK_UP"},
	{VK_RIGHT,  "VK_RIGHT"},
	{VK_DOWN,  "VK_DOWN"},
	{VK_SELECT,  "VK_SELECT"},
	{VK_PRINT,  "VK_PRINT"},
	{VK_EXECUTE,  "VK_EXECUTE"},
	{VK_SNAPSHOT,  "VK_SNAPSHOT"},
	{VK_INSERT,  "VK_INSERT"},
	{VK_DELETE,  "VK_DELETE"},
	{VK_HELP,  "VK_HELP"},
	{VK_LWIN,  "VK_LWIN"},
	{VK_RWIN,  "VK_RWIN"},
	{VK_APPS,  "VK_APPS"},
	{VK_SLEEP,  "VK_SLEEP"},
	{VK_NUMPAD0,  "VK_NUMPAD0"},
	{VK_NUMPAD1,  "VK_NUMPAD1"},
	{VK_NUMPAD2,  "VK_NUMPAD2"},
	{VK_NUMPAD3,  "VK_NUMPAD3"},
	{VK_NUMPAD4,  "VK_NUMPAD4"},
	{VK_NUMPAD5,  "VK_NUMPAD5"},
	{VK_NUMPAD6,  "VK_NUMPAD6"},
	{VK_NUMPAD7,  "VK_NUMPAD7"},
	{VK_NUMPAD8,  "VK_NUMPAD8"},
	{VK_NUMPAD9,  "VK_NUMPAD9"},
	{VK_MULTIPLY,  "VK_MULTIPLY"},
	{VK_ADD,  "VK_ADD"},
	{VK_SEPARATOR,  "VK_SEPARATOR"},
	{VK_SUBTRACT,  "VK_SUBTRACT"},
	{VK_DECIMAL,  "VK_DECIMAL"},
	{VK_DIVIDE,  "VK_DIVIDE"},
	{VK_F1,  "VK_F1"},
	{VK_F2,  "VK_F2"},
	{VK_F3,  "VK_F3"},
	{VK_F4,  "VK_F4"},
	{VK_F5,  "VK_F5"},
	{VK_F6,  "VK_F6"},
	{VK_F7,  "VK_F7"},
	{VK_F8,  "VK_F8"},
	{VK_F9,  "VK_F9"},
	{VK_F10,  "VK_F10"},
	{VK_F11,  "VK_F11"},
	{VK_F12,  "VK_F12"},
	{VK_F13,  "VK_F13"},
	{VK_F14,  "VK_F14"},
	{VK_F15,  "VK_F15"},
	{VK_F16,  "VK_F16"},
	{VK_F17,  "VK_F17"},
	{VK_F18,  "VK_F18"},
	{VK_F19,  "VK_F19"},
	{VK_F20,  "VK_F20"},
	{VK_F21,  "VK_F21"},
	{VK_F22,  "VK_F22"},
	{VK_F23,  "VK_F23"},
	{VK_F24,  "VK_F24"},
	{VK_NUMLOCK,  "VK_NUMLOCK"},
	{VK_SCROLL,  "VK_SCROLL"},
	{VK_OEM_NEC_EQUAL,  "VK_OEM_NEC_EQUAL"},
	{VK_OEM_FJ_JISHO,  "VK_OEM_FJ_JISHO"},
	{VK_OEM_FJ_MASSHOU,  "VK_OEM_FJ_MASSHOU"},
	{VK_OEM_FJ_TOUROKU,  "VK_OEM_FJ_TOUROKU"},
	{VK_OEM_FJ_LOYA,  "VK_OEM_FJ_LOYA"},
	{VK_OEM_FJ_ROYA,  "VK_OEM_FJ_ROYA"},
	{VK_LSHIFT,  "VK_LSHIFT"},
	{VK_RSHIFT,  "VK_RSHIFT"},
	{VK_LCONTROL,  "VK_LCONTROL"},
	{VK_RCONTROL,  "VK_RCONTROL"},
	{VK_LMENU,  "VK_LMENU"},
	{VK_RMENU,  "VK_RMENU"},
	{VK_BROWSER_BACK,  "VK_BROWSER_BACK"},
	{VK_BROWSER_FORWARD,  "VK_BROWSER_FORWARD"},
	{VK_BROWSER_REFRESH,  "VK_BROWSER_REFRESH"},
	{VK_BROWSER_STOP,  "VK_BROWSER_STOP"},
	{VK_BROWSER_SEARCH,  "VK_BROWSER_SEARCH"},
	{VK_BROWSER_FAVORITES,  "VK_BROWSER_FAVORITES"},
	{VK_BROWSER_HOME,  "VK_BROWSER_HOME"},
	{VK_VOLUME_MUTE,  "VK_VOLUME_MUTE"},
	{VK_VOLUME_DOWN,  "VK_VOLUME_DOWN"},
	{VK_VOLUME_UP,  "VK_VOLUME_UP"},
	{VK_MEDIA_NEXT_TRACK,  "VK_MEDIA_NEXT_TRACK"},
	{VK_MEDIA_PREV_TRACK,  "VK_MEDIA_PREV_TRACK"},
	{VK_MEDIA_STOP,  "VK_MEDIA_STOP"},
	{VK_MEDIA_PLAY_PAUSE,  "VK_MEDIA_PLAY_PAUSE"},
	{VK_LAUNCH_MAIL,  "VK_LAUNCH_MAIL"},
	{VK_LAUNCH_MEDIA_SELECT,  "VK_LAUNCH_MEDIA_SELECT"},
	{VK_LAUNCH_APP1,  "VK_LAUNCH_APP1"},
	{VK_LAUNCH_APP2,  "VK_LAUNCH_APP2"},
	{VK_OEM_1,  "VK_OEM_1"},
	{VK_OEM_PLUS,  "VK_OEM_PLUS"},
	{VK_OEM_COMMA,  "VK_OEM_COMMA"},
	{VK_OEM_MINUS,  "VK_OEM_MINUS"},
	{VK_OEM_PERIOD,  "VK_OEM_PERIOD"},
	{VK_OEM_2,  "VK_OEM_2"},
	{VK_OEM_3,  "VK_OEM_3"},
	{VK_OEM_4,  "VK_OEM_4"},
	{VK_OEM_5,  "VK_OEM_5"},
	{VK_OEM_6,  "VK_OEM_6"},
	{VK_OEM_7,  "VK_OEM_7"},
	{VK_OEM_8,  "VK_OEM_8"},
	{VK_OEM_AX,  "VK_OEM_AX"},
	{VK_OEM_102,  "VK_OEM_102"},
	{VK_ICO_HELP,  "VK_ICO_HELP"},
	{VK_ICO_00,  "VK_ICO_00"},
	{VK_PROCESSKEY,  "VK_PROCESSKEY"},
	{VK_ICO_CLEAR,  "VK_ICO_CLEAR"},
	{VK_PACKET,  "VK_PACKET"},
	{VK_OEM_RESET,  "VK_OEM_RESET"},
	{VK_OEM_JUMP,  "VK_OEM_JUMP"},
	{VK_OEM_PA1,  "VK_OEM_PA1"},
	{VK_OEM_PA2,  "VK_OEM_PA2"},
	{VK_OEM_PA3,  "VK_OEM_PA3"},
	{VK_OEM_WSCTRL,  "VK_OEM_WSCTRL"},
	{VK_OEM_CUSEL,  "VK_OEM_CUSEL"},
	{VK_OEM_ATTN,  "VK_OEM_ATTN"},
	{VK_OEM_FINISH,  "VK_OEM_FINISH"},
	{VK_OEM_COPY,  "VK_OEM_COPY"},
	{VK_OEM_AUTO,  "VK_OEM_AUTO"},
	{VK_OEM_ENLW,  "VK_OEM_ENLW"},
	{VK_OEM_BACKTAB,  "VK_OEM_BACKTAB"},
	{VK_ATTN,  "VK_ATTN"},
	{VK_CRSEL,  "VK_CRSEL"},
	{VK_EXSEL,  "VK_EXSEL"},
	{VK_EREOF,  "VK_EREOF"},
	{VK_PLAY,  "VK_PLAY"},
	{VK_ZOOM,  "VK_ZOOM"},
	{VK_NONAME,  "VK_NONAME"},
	{VK_PA1,  "VK_PA1"},
	{VK_OEM_CLEAR,  "VK_OEM_CLEAR"},
	{NULL, NULL }
};
TValueString g_NinNotifyValueString[]=
{
	{NIN_SELECT,  "NIN_SELECT"},
	{NIN_KEYSELECT,  "NIN_KEYSELECT"},
	{NIN_BALLOONSHOW,  "NIN_BALLOONSHOW"},
	{NIN_BALLOONHIDE,  "NIN_BALLOONHIDE"},
	{NIN_BALLOONTIMEOUT,  "NIN_BALLOONTIMEOUT"},
	{NIN_BALLOONUSERCLICK,  "NIN_BALLOONUSERCLICK"},
	{NIN_POPUPOPEN,  "NIN_POPUPOPEN"},
	{NIN_POPUPCLOSE,  "NIN_POPUPCLOSE"},
	{NULL, NULL }
};


static CHAR* GetMapValueStringAndOperate(TValueString Array[], int ArraySize, int Value)
{
	CHAR* Buffer = new CHAR[256];
	RtlZeroMemory(Buffer, 256);
	int Count = 0;
	for(int i = 0; i < ArraySize; i++)
	{
		TValueString* Vs = (TValueString*)&Array[i];

		if (Vs->Value == NULL && Vs->String == NULL)
				break;

		if ((Vs->Value & Value) == Vs->Value)
		{
			Count+= sprintf_s(Buffer+Count, 256-Count,"%s  ", Vs->String);
		}
	}


	return Buffer;
}

static CHAR* GetMapValueString(TValueString  Array[], int ArraySize ,int Value)
{
	for (int i = 0; i < ArraySize; i++)
	{
		if (Array[i].String == NULL )
			break;

		if (Array[i].Value == Value)
		{
			return Array[i].String;
		}
		
	}
	
	return NULL;
}

CHAR* GetGenericNotifyString(int NotifyCode)
{
	CHAR* Str;
	
	Str = GetMapValueString(g_WmNotifyGenericString, ARRAYSIZE(g_WmNotifyGenericString), NotifyCode);

	return Str;
}

LPCSTR GetVirtualKeyString(DWORD Value)
{
	return GetMapValueString(g_VirtualKeyString, ARRAYSIZE(g_VirtualKeyString), Value);
}



BOOL DebugFilterWindowMessage(USHORT Value)
{
	//WM_ERASEBKGND,
	USHORT Messages[]={WM_SETCURSOR, WM_NCHITTEST, WM_MOUSEFIRST, 0x1108,0x113e,WM_NCMOUSEMOVE};
	for(USHORT i = 0; i < ARRAYSIZE(Messages); i++)
	{
		if (Messages[i] == Value)
		{
			return TRUE;
		}
	}
	return FALSE;
}

CHAR* C32DbgGetWindowMsgString(UINT uMsg)
{
	if(g_C32DbgFlagWindowMsg && DebugFilterWindowMessage(uMsg))
		return NULL;
	CHAR* Str = GetMapValueString(g_WmString, ARRAYSIZE(g_WmString), uMsg);

	return Str;
}


VOID C32DbgOutWinowsMsg(USHORT Value, PCHAR Function)
{

	CHAR* Str = C32DbgGetWindowMsgString(Value);

	if (Str)
	{
		ZxDebug(("%s %s\n", Function,Str));
	}else
	{
		ZxDebug(("%s WMesage %x\n",Function, Value));
	}


}

#include <atlstr.h>

CString GetRetValue()
{
	CString XX;

	XX = L"123";

	return XX;
}

VOID C32StringTest()
{
	C32String Str1;

	Str1 += L"123";

	C32String Str2;

	Str2 = Str1;

	int i = 0;

}


VOID WINAPI C32DbgOutMsgPaint(LPPAINTSTRUCT lpps)
{
	CString xx;

	xx = GetRetValue();
	
	C32StringTest();

	C32String rcPaint;

	rcPaint = C32DbgGetStringRect(lpps->rcPaint);

	ZxDebug(("PaintStruct: rcPaint:%20ws fEarse : %4s fRestore : %4s fIncUpdate : %4s \n",
			rcPaint.GetString(), C32BoolToString(lpps->fErase),
			C32BoolToString(lpps->fRestore),
			C32BoolToString(lpps->fIncUpdate)));
}


/*
	Control Message
*/



VOID C32DbgOutWinowsMsgFilter(USHORT uMsg, WPARAM wParam, LPARAM lParam, PCHAR Prefix)
{
	if (g_C32DbgFlagWindowMsg == FALSE)
		return;
	
	if(DebugFilterWindowMessage(uMsg))
		return ;
	
	CHAR* Str = C32DbgGetWindowMsgString(uMsg);
	
	if (Str)
	{
		ZxDebug(("%s():: %s wParam: %p lParam: %p\n", Prefix,Str, wParam, lParam));
	}else
	{
		ZxDebug(("WM_MESSAGE %s: 0x%04X wParam: %p lParam: %p\n", Prefix, uMsg, (PVOID)wParam, (PVOID)lParam));
	}
}

CHAR* C32DbgGetTreeViewMsgString(UINT uMsg)
{
	CHAR* Str = GetMapValueString(g_TreeViewMessageString, ARRAYSIZE(g_TreeViewMessageString), uMsg);

	return Str;
}


VOID C32DbgOutTreeViewMsg(int MessageCode)
{
	CHAR* Str;

	Str = GetMapValueString(g_TreeViewMessageString, ARRAYSIZE(g_TreeViewMessageString), MessageCode);
	if (Str == NULL)
	{
		Str = C32DbgGetWindowMsgString(MessageCode);
	}

	if (Str)
	{
		ZxDebug(("TreeViewMessage:  %s \n", Str));
	}else
	{
		ZxDebug(("TreeViewMessage:  %d\n", MessageCode));
	}
}


static BOOL FilterTreeViewNotifyCode(int NotificationCode)
{

	static int  FilterArray[]=
	{ NM_SETCURSOR,NM_KILLFOCUS, -121, -177};
	BOOL bFilter = FALSE;

	for (int i = 0; i < ARRAYSIZE(FilterArray); i++)
	{
		if (FilterArray[i] == NotificationCode)
		{
			bFilter = TRUE;
			break;
		}
	}

	return bFilter;
}

VOID C32DbgOutTreeViewNotify(int NotificationCode, LPNMHDR NmHdr)
{
	CHAR * Str;

	if (FilterTreeViewNotifyCode(NotificationCode) == TRUE)
		return;

	Str = GetMapValueString(g_TreeViewNotifyString, ARRAYSIZE(g_TreeViewNotifyString), NotificationCode);
	if (Str)
	{
		ZxDebug(("TreeViewNotify: %s hwndFrom : %p Code : %x\n", Str, NmHdr->hwndFrom, NmHdr->code));
	}else
	{
		ZxDebug(("TreeViewNotify: %d hwndFrom : %p Code : %x\n", NotificationCode, NmHdr->hwndFrom, NmHdr->code));
	}

}

VOID C32DbgOutTreeViewNotify(int NotificationCode)
{
	CHAR * Str;

	if (FilterTreeViewNotifyCode(NotificationCode) == TRUE)
	{
		return;
	}
	Str = GetMapValueString(g_TreeViewNotifyString, ARRAYSIZE(g_TreeViewNotifyString), NotificationCode);
	if (Str)
	{
		ZxDebug(("TreeViewNotify: %s\n", Str));
	}else
	{
		ZxDebug(("TreeViewNotify: %d \n", NotificationCode));
	}

}


 CHAR* C32GetListViewNotifyString(int Nm)
{
	PCHAR Str;
	Str = GetMapValueString(g_ListViewNotifyString, ARRAYSIZE(g_ListViewNotifyString), Nm);
	if (Str == NULL)
	{
		Str = GetMapValueString(g_WmNotifyGenericString, ARRAYSIZE(g_WmNotifyGenericString), Nm);
	}
	if (Str == NULL)
	{
		Str="Unknown";
	}
	return Str;
}

CHAR* C32DbgGetTreeViewItemStateString(UINT State)
{
	CHAR* Str = GetMapValueStringAndOperate(g_TreeViewItemStateString, ARRAYSIZE(g_TreeViewItemStateString), State);

	return Str;
}


static BOOL FilterListViewNotifyCode(int NotificationCode)
{

	static int  FilterArray[]=
	{ NM_SETCURSOR,NM_KILLFOCUS, LVN_HOTTRACK, LVN_GETDISPINFO};
	BOOL bFilter = FALSE;

	for (int i = 0; i < ARRAYSIZE(FilterArray); i++)
	{
		if (FilterArray[i] == NotificationCode)
		{
			bFilter = TRUE;
			break;
		}
	}

	return bFilter;
}

static BOOL FilterHeaderNotifyCode(int NotificationCode)
{

	static int  FilterArray[]=
	{ NM_SETCURSOR,NM_KILLFOCUS};
	BOOL bFilter = FALSE;

	for (int i = 0; i < ARRAYSIZE(FilterArray); i++)
	{
		if (FilterArray[i] == NotificationCode)
		{
			bFilter = TRUE;
			break;
		}
	}

	return bFilter;
}


CHAR* C32DbgGetHeaderNotifyString(int NotifyCode)
{
	PCHAR Str = GetMapValueString(g_HeaderControlNotifyString, ARRAYSIZE(g_HeaderControlNotifyString), NotifyCode);
	if (!Str)
	{
		Str = GetGenericNotifyString(NotifyCode);
	}

	return Str;
}

VOID C32DbgOutHeaderNotify(int NotifyCode)
{
	if (g_C32DbgFlagHeaderNotify == FALSE)
		return;
	if(g_C32DbgFlagHeaderNotifyFilter)
	{
		if (FilterHeaderNotifyCode(NotifyCode))
			return;
	}
	PCHAR Str = C32DbgGetHeaderNotifyString(NotifyCode);
	if (Str)
	{
		ZxDebug(("HeaderControl:	%s \n", Str));
	}else
	{
		ZxDebug(("HeaderControlNotify: %d\n", NotifyCode));
	}

}

VOID C32DbgOutHeaderNotifyNmHeader(LPNMHEADER lpnmhdr)
{
	LPSTR Btn = (lpnmhdr->iButton == 0 ? "BTN_LEFT" :  lpnmhdr->iButton == 1 ? "BTN_RIGHT" : "BTN_MIDDLE");

	ZxDebug(("iItem : %d BtnType : %d hditem: %p \n", lpnmhdr->iItem, Btn, lpnmhdr->pitem));
}


VOID C32DbgOutListViewNotify(int Nm)
{
	if (g_C32DbgFlagLvNotify == FALSE)
		return;

	CHAR* Str;
	if (g_C32DbgFlagLvNotifyFilter == TRUE&& FilterListViewNotifyCode(Nm))
	{
		return;
	}
	Str = C32GetListViewNotifyString(Nm);

	if (Str)
	{
		ZxDebug(("LisViewNotify:	%s ,%d\n", Str, Nm));
	}else
	{
		ZxDebug(("ListViewNotify: %d\n", Nm));
	}


}

VOID C32DbgOutNmListView(LPNMLISTVIEW lpnmlv)
{
	if (g_C32DbgFlagLvNotify == FALSE)
		return;

	ZxDebug(("lpnmv : iItem : %8d iSubItem: %8d uNewState: 0x%08x uOldState: 0x%08x uChange: 0x%08x ptAction{%8d, %8d} lParam:%p \n",
			lpnmlv->iItem, lpnmlv->iSubItem, lpnmlv->uNewState, lpnmlv->uOldState, lpnmlv->uChanged, lpnmlv->ptAction.x, lpnmlv->ptAction.y, lpnmlv->lParam));

}


CHAR* C32DbgGetTabCtrlNotifyString(int Nm)
{
	PCHAR Str;
	Str = GetMapValueString(g_TabCtrlNotifyValueString, ARRAYSIZE(g_TabCtrlNotifyValueString), Nm);
	if (Str == NULL)
	{
		Str = GetMapValueString(g_WmNotifyGenericString, ARRAYSIZE(g_WmNotifyGenericString), Nm);
	}
	return Str;
}

VOID C32DbgOutTabCtrlNotify(int Nm)
{
	if (g_C32DbgFlagTabCtrlNotify == FALSE)
		return;

	char* Str;

	Str = C32DbgGetTabCtrlNotifyString(Nm);

	if (Str)
	{
		ZxDebug(("TabCtrlNotify:	%s ,%d\n", Str, Nm));
	}else
	{
		ZxDebug(("TabCtrlNotify: %d\n", Nm));
	}

}


CHAR* C32DbgGetToolTipCtrlNotifyString(int Nm)
{
	PCHAR Str;
	Str = GetMapValueString(g_ToolTipCtrlNotifyValueString, ARRAYSIZE(g_ToolTipCtrlNotifyValueString), Nm);
	if (Str == NULL)
	{
		Str = GetMapValueString(g_WmNotifyGenericString, ARRAYSIZE(g_WmNotifyGenericString), Nm);
	}
	return Str;
}

VOID C32DbgOutToolTipCtrlNotify(int Nm)
{
	if (g_C32DbgFlagToolTipCtrlNotify == FALSE)
		return;

	char* Str;

	Str = C32DbgGetToolTipCtrlNotifyString(Nm);

	if (Str)
	{
		ZxDebug(("ToolTipCtrlNotify:	%s ,%d\n", Str, Nm));
	}else
	{
		ZxDebug(("ToolTipCtrlNotify: %d\n", Nm));
	}

}

CHAR* C32DbgGetTrayNotifyString(DWORD NotifyCode)
{
	 char* Str = GetMapValueString(g_NinNotifyValueString, ARRAYSIZE(g_NinNotifyValueString), NotifyCode);
	 if (!Str)
	 {
		 Str = GetGenericNotifyString(NotifyCode);
		 if (Str == NULL)
		 {
			//Str = C32DbgGetWindowMsgString(NotifyCode);
			Str = GetMapValueString(g_WmString, ARRAYSIZE(g_WmString), NotifyCode);
		 }
	 }
	 return Str;
}



VOID WINAPI C32DbgOutRect(RECT& rc, CHAR* Pre)
{
	ZxDebug(("%s : rect: {%d, %d ,%d, %d} \n", Pre,rc.left, rc.top, rc.right, rc.bottom));
}

VOID WINAPI C32DbgOutRectPosSize(RECT& rc, CHAR* Pre)
{
	ZxDebug(("%s : rect: {%d, %d ,%d, %d} \n", Pre,rc.left,rc.top,rc.right-rc.left, rc.bottom - rc.top));
}

C32String  C32DbgGetStringRect(RECT& rc)
{
	C32String String;

	String.AssignStringW(40);

	String.FormatString(L"{%d, %d, %d, %d}", rc.left, rc.top, rc.right, rc.bottom) ;

	return String;

}

LPCSTR C32GetOwnerDrawCtrlType(UINT CtlType)
{
	LPCSTR Type = NULL;
	switch(CtlType)
	{
		case ODT_COMBOBOX:
			Type = "ODT_COMBOBOX";
			break;
		case ODT_LISTBOX:
			Type = "ODT_LISTBOX";
			break;
		case ODT_LISTVIEW:
			Type = "ODT_LISTVIEW";
			break;
		case ODT_MENU:
			Type = "ODT_MENU";
			break;
		case ODT_BUTTON:
			Type = "ODT_BUTTON";
			break;
		case ODT_STATIC:
			Type = "ODT_STATIC";
			break;
		case ODT_TAB:
			Type = "ODT_TAB";
			break;
		default:
			Type = "ODT_UNKNOWN";
			break;

	}

	return Type;
}


C32String C32FontGetString(HFONT hFont)
{
	C32String String;
	LOGFONT LogFont={};

	INT Bytes = GetObject(hFont, sizeof(LOGFONT), &LogFont);
	if (Bytes == 0)
	{
		String = L"GetObject()::Error";
	}else
	{
		String.FormatString(L"%s", LogFont.lfFaceName) ;
	}
	return String;
}

C32String C32FontGetString(HDC hDc)
{
	HFONT hFont = (HFONT)GetCurrentObject(hDc, OBJ_FONT);
	
	return C32FontGetString(hFont);
}

C32String C32FontGetString(HWND Hwnd)
{
	C32String String;
	HDC hDc = GetDC(Hwnd);
	String = C32FontGetString(hDc);

	ReleaseDC(Hwnd, hDc);

	return String;
}